/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectoedd;
import java.awt.BorderLayout;
import java.awt.Component;
import javax.swing.JFileChooser;
import java.io.File;
import java.io.FileReader;
import java.io.BufferedReader;
import javax.swing.JOptionPane;
import org.graphstream.graph.*;
import org.graphstream.graph.implementations.*;
import org.graphstream.ui.swing_viewer.*;
import org.graphstream.ui.view.View;
import org.graphstream.ui.view.Viewer;
/**
 *
 * @author
 */
public class Interfaz extends javax.swing.JFrame {
    Grafo graph;
    Ginfo info = new Ginfo();
    Graph grf = new SingleGraph("Grafo");
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interfaz.class.getName());

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        GraphPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Cargar Archivo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 120, 60));

        GraphPanel.setLayout(new java.awt.BorderLayout());
        getContentPane().add(GraphPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 590, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JOptionPane.showMessageDialog(rootPane, this.abrirarchivo(info));
        graph = new Grafo(info.usuarios.length);
        this.InsertarGinfo(graph, info);
        this.construirGrafo(graph, grf);
        this.actuaizar_Display();
    }//GEN-LAST:event_jButton1ActionPerformed

            public String abrirarchivo(Ginfo entrada){
            String aux1 = "";    
            String aux2 = "";
            String[] texto_relaciones = new String[2];
            int n=0;
            int userSize = 0;
            int relSize = 0;
            try{
                JFileChooser elegir_archivo = new JFileChooser();
                elegir_archivo.showOpenDialog(this);
                File aaa = elegir_archivo.getSelectedFile();
                if (aaa!=null){
                    FileReader arc = new FileReader(aaa);
                    BufferedReader read = new BufferedReader(arc);
                    while(!(aux1=read.readLine()).equals("relaciones")){
                        if (!aux1.equals("usuarios")){
                            userSize += 1;
                        }
                    }
                    while((aux1=read.readLine())!=null){
                        if (!aux1.equals("usuarios")){
                            relSize += 1;
                        }
                    }
                }
                
                entrada.usuarios = new String[userSize];
                entrada.relaciones = new String[relSize][2];
              
                File abrir = elegir_archivo.getSelectedFile();
                if (abrir!=null){
                    FileReader archivo=new FileReader(abrir);
                    BufferedReader leer=new BufferedReader(archivo);
                    while(!(aux2=leer.readLine()).equals("relaciones")){
                        if (!aux2.equals("usuarios")){
                            entrada.usuarios[n]=aux2;
                            n+=1;
                        }
                    }
                    n=0;
                    while((aux2=leer.readLine())!=null){
                        if (!aux2.equals("usuarios")){
                            texto_relaciones = aux2.split(", ");
                            entrada.relaciones[n][0] = texto_relaciones[0];
                            entrada.relaciones[n][1] = texto_relaciones[1];
                            n+=1;    
                        }
                    }
                    leer.close();
            }
            }catch(Exception a){
                return "Ocurrió un error al intentar leer el archivo";
            }
            return "Se ha leído el archivo exitosamente";
            }
            
            public void InsertarGinfo(Grafo g, Ginfo x){
                for(int i=0; i<x.usuarios.length; i++){
                    g.insertarVertice(x.usuarios[i]);
                }
               for(int i=0; i<x.relaciones.length; i++){
                   if(g.verticeExiste(x.relaciones[i][0]) && g.verticeExiste(x.relaciones[i][1])){
                       g.insertarArista(x.relaciones[i][1], g.posiciónVertice(x.relaciones[i][0]));
                   }
               }
            }
            
            public void construirGrafo(Grafo x, Graph display){
                Nodo aux = new Nodo(null);
                int i = 0;
                int j = 0;
                while(i<x.getVertices()){
                    display.addNode(x.getLista(i).primero().getDato().toString());
                    display.getNode(x.getLista(i).primero().getDato().toString()).setAttribute("ui.label", x.getLista(i).primero().getDato().toString());
                    display.getNode(x.getLista(i).primero().getDato().toString()).setAttribute("ui.style", "fill-color: cyan;size: 50px;");
                    i++;
                }
                i=0;
                while(i<x.getVertices()){
                    aux = x.getLista(i).primero();
                    while(aux!=null){
                        aux = aux.getpNext();
                        if(aux == null){
                            break;
                        }
                        display.addEdge(Integer.toString(i)+Integer.toString(j), x.getLista(i).primero().getDato().toString(), aux.getDato().toString(), true);
                        display.getEdge(Integer.toString(i)+Integer.toString(j)).setAttribute("ui.style", "fill-color: black;");
                        j++;
                    }
                   i++;
                   j=0;
                }
                display.setAttribute("ui.antialias");
            }
            
            public void actuaizar_Display(){
                SwingViewer viewer = new SwingViewer(grf, Viewer.ThreadingModel.GRAPH_IN_ANOTHER_THREAD);
                viewer.enableAutoLayout();
                View view = viewer.addDefaultView(true);
                view.openInAFrame(false);
                GraphPanel.add((Component) view, BorderLayout.CENTER);
            }
            
    public static void main(String args[]) {

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Interfaz().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GraphPanel;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
